name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Sync dependencies
        run: nix develop --command task sync

      - name: Check linter
        run: nix develop --command task lint

      - name: Check types
        run: nix develop --command task typecheck

  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        include:
          - python: "3.11"
            tox-env: "py311"
          - python: "3.12"
            tox-env: "py312"
          - python: "3.13"
            tox-env: "py313"
          - python: "3.14"
            tox-env: "py314"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Verify dev environment
        run: nix develop --command bash -c "uv --version && python${{ matrix.python }} --version"

      - name: Sync dependencies
        run: nix develop --command task sync

      - name: Run tests
        run: nix develop --command task test TOX_ENV=${{ matrix.tox-env }}
